node {
    checkout scm

    stage '001-create-files'
    sh "echo 'hello!' > hello.txt"
    sh "echo 'hello again!' > hello_again.txt"
    sh "mkdir greetings; echo 'hi' > greetings/hi.txt"
    sh "mkdir -p greetings/foo/bar; echo 'foo' > greetings/foo/bar/foo.txt"

    stage '002-delete-files'
    cleanWs()
}
